import type { SourceRecord } from './transform'

export type PickKind = 'pick' | 'prompt'

export interface PickEntry {
  seq: number
  kind: PickKind
  time: number
  id: string
  file: string
  line: number
  column: number
  component?: string
  /** Component hierarchy reported by the client, e.g. `App > TargetCard`. */
  chain?: string
  range: SourceRecord['range']
  /** Agent inboxes this pick was routed to. Empty means broadcast. */
  targets: string[]
  instruction?: string
  prompt?: string
}

/** Body posted to `/__pick-ai/record`. */
export interface RecordPayload {
  id?: string
  kind?: string
  chain?: string
  instruction?: string
  /** Target agent inbox, or empty/absent for broadcast. */
  target?: string
}

const TARGET_PATTERN = /^[a-z0-9][a-z0-9_-]{0,31}$/i

/** Keeps a target name safe to use as a file name, or returns undefined. */
export function sanitizeTarget(name: unknown): string | undefined {
  return typeof name === 'string' && TARGET_PATTERN.test(name) ? name : undefined
}

/** Sanitises, de-duplicates and preserves order of a configured target list. */
export function normalizeTargets(list: unknown): string[] {
  if (!Array.isArray(list)) return []
  const targets: string[] = []
  for (const item of list) {
    const target = sanitizeTarget(item)
    if (target && !targets.includes(target)) targets.push(target)
  }
  return targets
}

export function sourceOf(record: Pick<SourceRecord, 'file' | 'line' | 'column'>): string {
  return `${record.file}:${record.line}:${record.column}`
}

/**
 * Builds a single log entry from the server-side source record plus the short
 * payload the browser is allowed to send. Absolute paths never come from the
 * client — they are always resolved from the server-side record.
 */
export function buildPickEntry(
  record: SourceRecord,
  payload: RecordPayload,
  id: string,
  seq: number,
  time: number,
  target?: string,
): PickEntry {
  const instruction = typeof payload.instruction === 'string' ? payload.instruction.trim() : ''
  const chain = typeof payload.chain === 'string' && payload.chain ? payload.chain : undefined
  const kind: PickKind = payload.kind === 'prompt' && instruction ? 'prompt' : 'pick'

  const entry: PickEntry = {
    seq,
    kind,
    time,
    id,
    file: record.file,
    line: record.line,
    column: record.column,
    component: record.component,
    chain,
    range: record.range,
    targets: target ? [target] : [],
  }

  if (kind === 'prompt') {
    entry.instruction = instruction
    entry.prompt = `${instruction}\n\nsrc: ${sourceOf(record)}\nrange: ${chain ?? record.component ?? 'UnknownComponent'}`
  }
  return entry
}

/** Renders a human/agent friendly snapshot of the latest pick. */
export function renderLastPick(entry: PickEntry): string {
  const chain = entry.chain ?? entry.component ?? 'UnknownComponent'
  const body = entry.instruction ? entry.instruction : '_（未填写，用户仅选取了元素）_'
  return [
    '<!-- Generated by vite-plugin-pick-ai. Do not edit by hand. -->',
    `# Pick AI · seq ${entry.seq}`,
    '',
    `- **src**: \`${sourceOf(entry)}\``,
    `- **range**: ${chain}`,
    `- **component**: ${entry.component ?? 'Unknown'}`,
    `- **target**: ${entry.targets.length ? entry.targets.join(', ') : '全部'}`,
    `- **kind**: ${entry.kind}`,
    `- **time**: ${new Date(entry.time).toISOString()}`,
    '',
    '## 修改要求',
    '',
    body,
    '',
  ].join('\n')
}

/** Parses an append-only JSONL log, skipping blank or malformed lines. */
export function parseEntries(jsonl: string): PickEntry[] {
  const entries: PickEntry[] = []
  for (const line of jsonl.split('\n')) {
    if (!line.trim()) continue
    try {
      entries.push(JSON.parse(line) as PickEntry)
    } catch {
      // Ignore a partially written trailing line.
    }
  }
  return entries
}

/** One-shot push request written by the browser. */
export interface PushControl {
  /** Epoch ms of the last one-shot push request; 0 when none. */
  once: number
  /** Target agent for the request; empty means broadcast. */
  target: string
}

export function defaultPushControl(): PushControl {
  return { once: 0, target: '' }
}

/** Parses `push.json`, tolerating missing or malformed input. */
export function parsePushControl(raw: string): PushControl {
  try {
    const value = JSON.parse(raw) as Partial<PushControl>
    return {
      once: typeof value.once === 'number' && value.once > 0 ? value.once : 0,
      target: typeof value.target === 'string' ? value.target : '',
    }
  } catch {
    return defaultPushControl()
  }
}
